### PR TITLE
QUICKSTEP-46 Fault tolerance in bulk loading data

### PR DESCRIPTION
**Pull request by tarunbansal**
This PR helps add fault tolerance while bulk loading data from a file. Now quickstep will skip a record(a row) if it is faulty and move to the next one. Possible error cases are listed below and further classified as To-do or Done :
DONE
1) Record has too few fields.
2) Record has too many fields.
3) A field could not be parsed properly as per the attribute type in a schema.
4) Null literal specified for a column with a not nullable type.
TO-DO
5) Null character mixed in with other data for a column.
6) Backslash line splicing support.

### CODE REVIEW

**Comment by pateljm** [comment]
@tarunbansal This looks good. May I request adding a test to show this error message? Perhaps by augmenting tests/TextScanOperator_unittest.cpp? Then squash the commits, and this is good to go!

@hakanmemisoglu @hbdeshmukh If @tarunbansal could you walk him through the testing infrastructure and show him the ropes? Thanks!

**Comment by zuyu** [comment]
@tarunbansal This feature is great, and I was wondering if we would consider dumping the original faulty tuples at the end, instead of ignoring them all. Thanks!

**Comment by tarunbansal** [comment]
@pateljm Thanks. I will add the suggested test after a discussion with @hbdeshmukh @hakanmemisoglu about the testing infrastructure. 
@zuyu Thanks for your suggestion. Moving the original faulty tuples at the end of the data file will need additional write permissions as compared to the current read mode we are using for loading the data. Should that be done in a future PR?

**Comment by pateljm** [comment]
@zuyu IMHO it would be odd to modify the data file. Thanks for looking at this PR. 
@tarunbansal I think this PR is good as it is.

**Comment by zuyu** [comment]
@tarunbansal To clarify, I mean to dump the flaky tuples `at the end` of query execution, either to `stdout` or a new file.

**Comment by pateljm** [comment]
@zuyu I'd suggest move this feature along and not expand the scope unnecessarily. There is a tradeoff -- one can dump the line numbers of the problematic tuples, but that slows down loading. For now, I'd suggest to wrap this feature and not load it with more. Thanks.

**Comment by hbdeshmukh** [comment]
Based on a discussion between @tarunbansal, @hakanmemisoglu and I - we noted two things: 
1. Logging error messages to std::cout could be unhelpful when there are multiple threads trying to load the data. The error messages will get mixed up with each other. For now, @tarunbansal decided to log the error messages (using GLOG) to the log file. Later, we can summarize the error messages using thread-private buffers and emit them at the end of each work order execution.
 
2. @tarunbansal will look at how the current testing framework for TextScan operator and add tests with corrupt input tuples. The testing would involve loading an input with some corrupt tuples and verifying if the correct tuples got inserted. 

Once the above comments are addressed and the commits are squashed in one, we will be good to go. Thanks @pateljm @zuyu for your inputs.

**Comment by zuyu** [comment]
@hbdeshmukh Sg to me.

**Comment by tarunbansal** [comment]
Thanks for demonstrating me the testing infrastructure @hakanmemisoglu and @hbdeshmukh.  As discussed I have added a test case where some faulty records are present. Also logged the error messages to the log file instead of logging them to stdout.
Created a single commit for all the changes done so far. Please have a look and merge this PR if it is good to go now.

**Comment by zuyu** [comment]
@tarunbansal I believe we also need to include the new unit test in `CMakeLists.txt` (as [here](https://github.com/apache/incubator-quickstep/blob/master/relational_operators/CMakeLists.txt#L771)) to actually run the faulty one.

**Comment by tarunbansal** [comment]
@zuyu Thanks. I have now included the test in cmake file.

**Comment by pateljm** [comment]
@tarunbansal Can you rebase again? Sorry - with the other commits, now this rebase is off (one of the limitations of git on ASF). Thanks!

**Comment by tarunbansal** [comment]
@pateljm Rebased it. Please merge this PR if it is good to go now. Thanks.

**Comment by tarunbansal** [comment]
Rebased it again to be in synch with the latest commits @hbdeshmukh @pateljm . Please merge this PR if everything looks okay. Thanks !

**Comment by pateljm** [comment]
@tarunbansal I can close this. Can you rebase? Thanks!

**Comment by tarunbansal** [comment]
@pateljm Rebase done.

**Comment by pateljm** [comment]
@tarunbansal Merged. Thanks for this contribution!

**Pull request merged**
