### PR TITLE
Constructed Generators once in the optimizer.

### PR DESCRIPTION
**Pull request by zuyu**
Instead of creating generators each time per query, do so once, and reuse the instances for every query.

### CODE REVIEW

**Comment by zuyu** [comment]
@jianqiao I need your input on the correctness of this PR if we have concurrent queries running. Thanks!

**Comment by jianqiao** [comment]
@zuyu The `Generator`'s can be stateless (need some refactoring), but each query should have its own `OptimizerContext`.

**Comment by zuyu** [comment]
@jianqiao Thank you for your comments.

What do you think if we move `OptimizerContext` from `Optimizer` to `QueryHandle`, which is unique per query?

**Comment by jianqiao** [comment]
That sounds good. Note that the refactoring needs quite some work to pass `optimizer_context` around, especially in `ExecutionGenerator`.

**Pull request closed without merging**
