### PR TITLE
Fixed the time measurement from milli to microseconds in Worker

### PR DESCRIPTION
**Pull request by hbdeshmukh**

### CODE REVIEW

**Comment by hakanmemisoglu** [comment]
It seems alright. I am merging it.

**Comment by hbdeshmukh** [comment]
Hi @hakanmemisoglu 

Did you delete the branch after merging? If not, you can follow the instructions here: https://cwiki.apache.org/confluence/display/QUICKSTEP/Workflow+For+Committers

**Comment by hakanmemisoglu** [comment]
@hbdeshmukh, thank you for the notification.
I have already followed the instructions. Actually the branch is not in original Apache repo, however it is accessible from GitHub.

**Comment by zuyu** [comment]
Yes, it is in a wired situation.

@hbdeshmukh How did you create this branch? What is the `origin` for your local forked repo showed by `git remote -v`?

**Comment by hbdeshmukh** [comment]
```
git remote -v

mirror  https://github.com/apache/incubator-quickstep.git (fetch)
mirror  https://github.com/apache/incubator-quickstep.git (push)
origin  https://git-wip-us.apache.org/repos/asf/incubator-quickstep.git (fetch)
origin  https://git-wip-us.apache.org/repos/asf/incubator-quickstep.git (push)
```

**Pull request merged**
