### PR TITLE
Refactored messages processing in both PolicyEnforcer and QueryManager.

### PR DESCRIPTION
**Pull request by zuyu**
This PR simplifies the message processing logics in both `PolicyEnforcer` and `QueryManager`.

### CODE REVIEW

**Comment by zuyu** [comment]
Assigned to @hbdeshmukh. Thanks!

**Comment by pateljm** [comment]
LGTM. @hbdeshmukh Ok if I close?

**Comment by pateljm** [comment]
@zuyu I'm ready to close this. Can you rebase with the master? Thanks! 
@hbdeshmukh I take it that you have no concerns.

**Comment by hbdeshmukh** [comment]
Hi @pateljm @zuyu Apologies for the delay. This looks good to me. 

@zuyu Can you run some SSB queries for sanity testing? I usually do that after a code change in the scheduler.

**Comment by zuyu** [comment]
@hbdeshmukh Good suggestions. I'll let you know after I finish the sanity checks, and report the numbers.

**Comment by pateljm** [comment]
@zuyu reported a 3% improvement on SSB. Merging now.

**Pull request merged**
