### PR TITLE
QUICKSTEP-38. Add support for python3 to utility scripts

### PR DESCRIPTION
**Pull request by cwelton**
Three core changes:
- update from python2 print command, to python3 print function [1]
- switch from xrange to range [1]
- switch from dict.iteritems to iter(dict.items())  [2]

[1] http://python-future.org/compatible_idioms.html
[2] http://legacy.python.org/dev/peps/pep-0469/

### CODE REVIEW

**Comment by pateljm** [comment]
This looks good Caleb (@cwelton)! Can you rebase so that I can merge this commit? Thanks!

**Comment by cwelton** [comment]
Rebase complete

**Comment by pateljm** [comment]
Thanks @cwelton! Merged to master.

**Comment by zuyu** [comment]
@pateljm We need to reverse this merge, due to an incorrect rebase.

@cwelton We expect a different rebase result where this PR only contains a single commit ahead of the `origin/master`, instead of having another unrelated commit from a merged PR.

**Comment by cwelton** [comment]
Ah, sorry, just thought you wanted the extraneous merge commit squashed.  I've reordered the commits in my branch.  For some reason the hashjoin commit is still showing up in this PR, not sure why.

**Comment by zuyu** [comment]
@cwelton No worry for this PR. I've addressed the issues in the `master` branch. Thanks again for submitting a PR.

Next time if we run `git fetch origin/master` and then `git rebase -i origin/master`, I think we are good to go.

Cheers!

**Comment by cwelton** [comment]
Thanks for fixing, I suggest adding a contributor's guide with your suggested git workflow, to help streamline future contributors/contributions.

**Comment by zuyu** [comment]
Yes, we should add a workflow for contributors as well. Stay tuned!

**Comment by zuyu** [comment]
@cwelton I've created [the guideline](https://cwiki.apache.org/confluence/display/QUICKSTEP/Workflow+For+Contributors) as suggested. Cheers!

**Pull request merged**
