### PR TITLE
QUICKSTEP-20: RANGE mode and computation optimization

### PR DESCRIPTION
**Pull request by shixuan-fan**
- Supported RANGE mode for window aggregation.
- Optimized the AVG calculation time complexity from O(nk) to O(n), where n is the number of tuples and k is the window size.

### CODE REVIEW

**Comment by shixuan-fan** [comment]
Does anybody know why Travis CI keeps saying "apt-get install failed" for all the checks? Thanks a lot :)

**Comment by hbdeshmukh** [comment]
May be some connection issue with the llvm repos. Did you try restarting the travis build?

**Comment by shixuan-fan** [comment]
@hbdeshmukh I tried twice this morning and it didn't work. Just restarted it again and hopefully this time everything will be fine :) Thanks!

**Comment by pateljm** [comment]
@shixuan-fan LGTM. Ready to merge. Can you rebase?

**Comment by shixuan-fan** [comment]
@pateljm Done. Thanks!

**Pull request merged**
