### PR TITLE
Removed redundant third party libraries.

### PR DESCRIPTION
**Pull request by zuyu**
`gflags` and `gtest`, shared by both Quickstep and TMB.

Tested in a cloudlab machine (Ubuntu 14.04 LTS and LLVM 3.7, the same compiler used in the Travis CI).

### CODE REVIEW

**Comment by zuyu** [comment]
Assigned to @cramja.

**Comment by cramja** [comment]
+1

**Comment by pateljm** [comment]
+1 from me too. Thanks @zuyu! Cross gluttony off for this part from the [7 deadly sins of software development](http://www.infoworld.com/article/2623349/application-development/the-7-deadly-sins-of-software-development.html).

**Comment by zuyu** [comment]
@cramja The [initial CI tests](https://travis-ci.org/apache/incubator-quickstep/builds/208755951) passed. If we are blocked by this PR for the release, I think we could merge now.

**Comment by cramja** [comment]
That would be great.

**Comment by cramja** [comment]
@zuyu I'll merge it now because Travis is acting up and I saw your earlier CI.

**Comment by cramja** [comment]
@zuyu FYI I merged this branch and it appears as merged in the apache repo but it seems as though the git mirror is lagging behind.

I can close it once it updates, or please do if you see it first.

**Comment by zuyu** [comment]
Just wait for the GitHub to sync with the ASF repo, and it will automatically close this PR.

**Pull request closed without merging**
