### PR TITLE
Change the vector elision from `none` to `selection`

### PR DESCRIPTION
**Pull request by pateljm**
The default VECTOR_COPY_ELISION_LEVEL is selection, so test that instead of none.

### CODE REVIEW

**Comment by zuyu** [comment]
@pateljm How about trying with all the four options to see the time to take, and then go with there?

**Comment by navsan** [comment]
GCC with VECTOR_COPY_ELISION_LEVEL=Selection failed in both debug and release modes. It's the same internal compiler error. 

Does the number of concurrently running jobs affect the amount of memory available to each? If so, we should definitely not bump up the number of build types.

**Comment by zuyu** [comment]
No, the total memory would be the same. `gcc` maybe just do not spend memory resource wisely.

**Comment by navsan** [comment]
@pateljm I think you should set MAKE_JOBS to 1 for Selection as well.

**Comment by pateljm** [comment]
Good suggestion @navsan! Trying it now. Sad that `gcc` is fragile can can't deal with a parallel make.

**Comment by zuyu** [comment]
@pateljm Before merging this PR, we need to rebase w/ master to get rid of previous merged commits.

**Comment by zuyu** [comment]
@pateljm You might want to try add back the else case of `MAKE_JOBS=2` for `clang`.

**Comment by pateljm** [comment]
Creating a new PR tied to JIRA.

**Pull request closed without merging**
