### PR TITLE
TMB: Added Support for an Empty, but Typed TaggedMessage.

### PR DESCRIPTION
**Pull request by zuyu**
This constructor avoids creating [a dummy payload](https://github.com/apache/incubator-quickstep/blob/master/query_execution/ForemanSingleNode.cpp#L171).

### CODE REVIEW

**Comment by hbdeshmukh** [comment]
Hi @zuyu 
This looks good to me. Do you plan to change the example that you have linked in the description in the same PR or a separate PR?

**Comment by zuyu** [comment]
@hbdeshmukh Thanks for the review.

If [the change](https://github.com/apache/incubator-quickstep/commit/77e8b3a72bfc0f7119b95e1cc769fa741e70c4aa) looks good to you, we could merge in the same PR.

**Comment by zuyu** [comment]
@hbdeshmukh Please take a look this PR regarding some follow-up changes to apply this new `TaggedMessage` type.

Note that the CI failed due to some repo fetches, not related to this PR.

**Comment by hbdeshmukh** [comment]
Sure @zuyu 

I will take a look at the changes.

**Comment by hbdeshmukh** [comment]
Hi @zuyu 

Looks good to me. As the travis failure is unrelated to the PR, and 5 of the 8 build configurations have passed, so I am merging the PR.

**Pull request merged**
